name = "Matchsticks"
uuid = "c3f74eca-32df-4283-859a-5d5175949bbe"
authors = ["Patrick Armstrong <patrick.armstrong@anu.edu.au>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
